"""some changes on the database Field

Revision ID: 34255a1ec929
Revises: d57635a9054a
Create Date: 2021-05-31 10:29:55.340429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34255a1ec929'
down_revision = 'd57635a9054a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('token_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users_table', ['token_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_table', type_='unique')
    op.drop_column('users_table', 'token_id')
    # ### end Alembic commands ###
